# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.CharField(blank=True, default='Switch1', max_length=100)),
                ('room', models.CharField(blank=True, default='Living Room', max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='ON')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
