# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='switch',
            field=models.CharField(blank=True, default='SW1', max_length=100),
        ),
    ]
